<div class="second-footer">
    <button class="click_me_button" type="button">Click me</button>

    <div class="game_modal_overlay is-hidden">
        <div class="game_modal">
            <div class="game_modal_content">
                <button class="close_button" type="button">x</button>
                <p>guessing game</p>
                <p>You need to guess a randomly generated number from 1 to 50 by entering numbers into a box and clicking a button that reads "guess"</p>
                <input class="game_modal_input" type="text">
                <p class="message-el"></p>
                <button class="guess_button" type="button">Guess</button>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".second-footer": {
            "stohnii":{}
        }
    }
</script>