<div class="second-footer" data-bind="scope: 'stohniifooter'">
    <button class="click_me_button" type="button" data-bind="click: clickMeButton">Click me</button>

    <div class="game_modal_overlay is-hidden">
        <div class="game_modal">
            <div class="game_modal_content">
                <button class="close_button" type="button" data-bind="click: closeButton">x</button>
                <p class="game_modal_title">guessing game</p>
                <p>You need to guess a randomly generated number from 1 to 50 by entering numbers into a box and clicking a button that reads "guess"</p>
                <input class="game_modal_input" type="text">
                <ul class="numbers-el" data-bind="foreach: numbers">
                    <li class="number-el" data-bind="text: $data"></li>
                </ul>
                <p class="message-el" data-bind="text: message"></p>
                <button class="guess_button" type="button" data-bind="click: guessButton">Guess</button>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".second-footer": {
            "stohnii":{}
        },
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "stohniifooter": {
                        "component": "Stohnii_SecondFooter/js/kosecond-footer"
                    }
                }
            }
        }
    }
</script>
