<div class="overlay is-hidden">
    <div class="modal">
        <div class="modal_content">
            
            <img class="modal_img" src="https://wp4all.co.il/wp-content/uploads/2019/06/%D7%AA%D7%9E%D7%95%D7%A0%D7%94-%D7%A6%D7%95%D7%A8-%D7%A7%D7%A9%D7%A8.png" alt="Contact Us Image">
            
            <div>
                <h2 class="modal_title">Contact us</h2>

                <form class="modal_form">
                <input class="form_input" placeholder="Username"/>
                <input class="form_input" placeholder="Email"/>
                <textarea class="form_txt" placeholder="Message..."></textarea>
                <button class="form_btn" type="button">
                    Send message →
                </button>
                </form>

                <div class="modal_btn">
                <button class="modal_btn--cancel" type="button">Cancel</button>
                <button class="modal_btn--close" type="button">Don't show again</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "alias":{}
        }
    }
</script>